In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a.dtype)

b = np.array([1.2, 2.3, 4.5])
print(b.dtype)

c = np.array(['siva', 'tony', 'abi'])
print(c.dtype)

int64
float64
<U4


In [8]:
#  Force a data type:
a = np.array([1,2,3,4,5],dtype = 'float')
print(a)
print(a.dtype)

[1. 2. 3. 4. 5.]
float64


In [28]:
#  2. Array Attributes (properties/info about the array)
# These help you understand the structure of your array.

# ndim → Number of dimensions

one_d = np.array([1,2,3,4,5])
print(one_d)
print('one dimension array :',one_d.ndim)
print('-'*20)

two_d = np.array([[1,2,3],[4,5,6]])
print(two_d)
print('two dimension array :', two_d.ndim)
print('-'*20)

three_d = np.array([
    [[1,2,3],[4,5,6]], 
    [[3,2,1],[6,5,4]]
                   ])  # multiple matrices is the 3 dimensional, or 3d mean like image
print(three_d)
print('three dimension array :',three_d.ndim)
print('-'*20)

print(one_d.shape)
print('-'*20)
print('2 row 3 column')
print(two_d.shape)
print('-'*20)
print()
print('output:',three_d.shape) # output: (2, 2, 3)  ----> this mean:
'''

explanation about: print('output:',three_d.shape)

[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]
three dimension array : 3

2 → You have 2 matrices (or 2 blocks)

2 → Each matrix has 2 rows

3 → Each row has 3 columns/elements

So the shape is (blocks, rows, columns) = (2, 2, 3)


'''
print('size:',three_d.size)

# convetr datatype from int to float in 3d matrix
float_three_d = three_d.astype(float)
print(float_three_d.dtype)



[1 2 3 4 5]
one dimension array : 1
--------------------
[[1 2 3]
 [4 5 6]]
two dimension array : 2
--------------------
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]
three dimension array : 3
--------------------
(5,)
--------------------
2 row 3 column
(2, 3)
--------------------

output: (2, 2, 3)
size: 12
float64


In [55]:
'''
✅ What is .itemsize?
.itemsize tells you:

💡 "How much memory (in bytes) each element in the NumPy array takes."
'''
# Especially useful when working with large datasets in data analysis or machine learning.

a = np.array([1,2,3,4,5], dtype = np.int32)
print('a :',a)
print('datatype :', a.dtype)
print('each element size in bytes :', a.itemsize) # How much memory does one item take?
print('total memory of this array: ', a.nbytes) # How much memory does the whole array take?
print('-'*20)

b = np.array([1.2, 2.2, 3.3, 4.5, 5.1], dtype = np.float32)
print('b:', b)
print('datatype :',b.dtype)
print('each element size in bytes :', b.itemsize) #.itemsize mean : Meaning: Size (in bytes) of a single element in the array or How much memory does one item take? 
print('Total memory used by the array:', b.nbytes) # 🔸 nbytes →Total memory (in bytes) used by the entire array or "How much memory does the whole array take?"

# So, NumPy only supports types that fit cleanly in 1, 2, 4, or 8 bytes

a : [1 2 3 4 5]
datatype : int32
each element size in bytes : 4
total memory of this array:  20
--------------------
b: [1.2 2.2 3.3 4.5 5.1]
datatype : float32
each element size in bytes : 4
Total memory used by the array: 20


In [10]:
# transpose
import numpy as np
a = np.array([[1,2],
              [3,4]])

print("normal :")
print(a)
print()
print('after transpose:')
print(a.T)



normal :
[[1 2]
 [3 4]]

after transpose:
[[1 3]
 [2 4]]
