In [27]:
# ✅ NumPy – Array Operations (Full Guide + Tasks)
'''
 1. Arithmetic Operations
Add, Subtract, Multiply, Divide, Power, Modulus
'''
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4,5,6])
print('add :',a+b)
print('sub :',a-b)
print('mul :', a*b)
print('div :', a/b)
print('modu:', a%b)
print()
print('-'*20)

#  2. Comparison Operations
print(a>b)
print(a<b)
print(a==b)
print()
print('-'*20)

'''
3. Logical Operations
Use: np.logical_and(), np.logical_or(), np.logical_not()
# Create two arrays and apply logical operations to filter values.

'''
a = np.array([1, 2, 3,7,8,9])
b = np.array([4,5,6,7,1,17])
res = np.logical_and(a>5,b>5)
print(a[res])
print(b[res])

'''
a = [False, False, False, True, True, True]
b = [False, False, True, True, False, True]

works like this:
True and True → True

True and False → False

False and True → False

False and False → False
'''
print()
print('-'*20)
print('OR operation:')
print('a: ',a>5)
print('b:',b>5)
print()
print('res:',np.logical_or(a>5, b>5))
print()
print('-'*20)
print('Not operation')
print('a: ',a>5)
print('b:',b>5)
print()
print('a res:',np.logical_not(a>5))
print('b res:',np.logical_not(b>5))





add : [5 7 9]
sub : [-3 -3 -3]
mul : [ 4 10 18]
div : [0.25 0.4  0.5 ]
modu: [1 2 3]

--------------------
[False False False]
[ True  True  True]
[False False False]

--------------------
[7 9]
[ 7 17]

--------------------
OR operation:
a:  [False False False  True  True  True]
b: [False False  True  True False  True]

res: [False False  True  True  True  True]

--------------------
Not operation
a:  [False False False  True  True  True]
b: [False False  True  True False  True]

a res: [ True  True  True False False False]
b res: [ True  True False False  True False]


In [49]:
'''
🔸 4. Aggregate Functions (Axis wise)
sum(), mean(), min(), max(), std(), var(), cumsum()
'''
a = np.array([[1,2,3],
              [4,5,6]])
print('axis 0 means column wise, sum: ',a.sum(axis = 0))
print('axis 1: row wise, sum: ',a.sum(axis = 1))
print()
print('axis 0 :mean :',a.mean(axis = 0))
print('axis 1 :mean :', a.mean(axis =1))
print()
print('axis 0 :min :', a.min(axis = 0))
print('axis 1: min :', a.min(axis = 1))
print()
print('axis 0 means column wise: std :', a.std(axis = 0))
print('axis 1: row wise: std:', a.std(axis = 1))
print()
print('axis 0 means column wise: var:',a.var(axis = 0))
print('axis 1: row wise: var: ',a.var(axis = 1))
print()
print('-'*20)
print(a)
print()
print('axis 0 means column wise: cumsum:')
print( a.cumsum(axis = 0))
print()
print('axis 1 means row wise: cumsum:')
print( a.cumsum(axis = 1))
print()

axis 0 means column wise, sum:  [5 7 9]
axis 1: row wise, sum:  [ 6 15]

axis 0 :mean : [2.5 3.5 4.5]
axis 1 :mean : [2. 5.]

axis 0 :min : [1 2 3]
axis 1: min : [1 4]

axis 0 means column wise: std : [1.5 1.5 1.5]
axis 1: row wise: std: [0.81649658 0.81649658]

axis 0 means column wise: var: [2.25 2.25 2.25]
axis 1: row wise: var:  [0.66666667 0.66666667]

--------------------
[[1 2 3]
 [4 5 6]]

axis 0 means column wise: cumsum:
[[1 2 3]
 [5 7 9]]

axis 1 means row wise: cumsum:
[[ 1  3  6]
 [ 4  9 15]]



In [51]:
'''
5. Broadcasting
Operations between different shape
'''
a = np.array([1,2,3])
b = 2
print(a+b)
print()
print('-'*20)

# # Multiply a 1D array by a scalar and another 1D array of shape (3,)
a = np.array([4,5,6])
b = 2
print(a+b)

[3 4 5]

--------------------
[6 7 8]


In [61]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print('dot matrics:')
print('three types model is there like (np.dot(), np.matmul(), @)')
print()
print(np.dot(a, b))
print()
print(np.matmul(a,b))
print()
print(a@b)



dot matrics:
three types model is there like (np.dot(), np.matmul(), @)

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [62]:
#  7. Element-wise vs Matrix Multiplication

a = np.array([[1, 2], 
              [3, 4]])

b = np.array([[5, 6], 
              [7, 8]])
print(a*b)

[[ 5 12]
 [21 32]]


In [8]:
#  Modifying Array Elements

import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a>5] = 10
print(a)
print()
print('-'*20)
# Replace all odd numbers with -1 in a given array.
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2 !=0] = -1
print(a)


[ 1  2  3  4  5 10 10 10 10 10]

--------------------
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [11]:
'''
 9. Clip Function
Limit values to a min and max
'''
# np.clip(array, min_value, max_value)
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.clip(a,2,7))
'''
🔍 How it works:
Each element in the array is checked:

If it’s less than min_value, it's replaced with min_value.

If it’s greater than max_value, it's replaced with max_value.

If it’s in between, it remains unchanged.
'''
# task;
a = [1,2,3,4,5,6,7,8,9,10,12,20,15,18,17,19,21]
print(np.clip(a,10,20))

[2 2 3 4 5 6 7 7 7 7]
[10 10 10 10 10 10 10 10 10 10 12 20 15 18 17 19 20]


In [17]:
#10. Rounding Functions
#np.round(), np.floor(), np.ceil()

a = np.array([1.2, 2.5, 3.7, 4.5, 5.9, -1.3, -2.5, -3.7, -4.5, 0.5, -0.5, 6.01, -6.99])
print('round: ',np.round(a)) # Rounds each element to the nearest whole number.
print('-'*20)
print('floor :',np.floor(a)) # Rounds each number down to the nearest whole number, even if it's a decimal like 4.9.
print('-'*20)
print('ceil :', np.ceil(a)) # Rounds each number up to the next whole number.

round:  [ 1.  2.  4.  4.  6. -1. -2. -4. -4.  0. -0.  6. -7.]
--------------------
floor : [ 1.  2.  3.  4.  5. -2. -3. -4. -5.  0. -1.  6. -7.]
--------------------
ceil : [ 2.  3.  4.  5.  6. -1. -2. -3. -4.  1. -0.  7. -6.]


In [37]:
'''
# Create a 4x4 matrix with random numbers from 1 to 100
# 1. Replace all even numbers with 0
# 2. Find sum of each row
# 3. Find mean of each column
# 4. Normalize the matrix (subtract mean and divide by std)

'''
a = np.random.randint(1,101, size = (4, 4))
print(a)
print()

#Replace all even numbers with 0
a[a%2 == 0] = 0
print(a)
print()

# Find sum of each row
print(a.sum(axis = 1))
print()

#  Find mean of each column
print(a.mean(axis = 0))
print()

# Normalize the matrix (subtract mean and divide by std)

mean = a.mean(axis = 0)
std = a.std(axis = 0)
sub = a-mean
res = sub/std
print('std :', std)
print()
print(res)


[[11 91 81 60]
 [77 32 88 61]
 [14 16 19 30]
 [ 9 81  3 72]]

[[11 91 81  0]
 [77  0  0 61]
 [ 0  0 19  0]
 [ 9 81  3  0]]

[183 138  19  93]

[24.25 43.   25.75 15.25]

std : [30.73576906 43.14510401 32.70607742 26.41377482]

[[-0.43109382  1.11252484  1.68928849 -0.57735027]
 [ 1.71624142 -0.99663684 -0.78731545  1.73205081]
 [-0.78898302 -0.99663684 -0.20638366 -0.57735027]
 [-0.49616458  0.88074883 -0.69558938 -0.57735027]]


In [70]:
# tasks
# ✅ Task 1: Multiply every element by 10
arr = np.array([1, 2, 3, 4, 5])
mul = arr*10
print(mul)
print()

# Task 2: Add 5 to every even element
arr = np.array([1, 2, 3, 4, 5])
arr[arr%2==0] +=5 # direct update
print(arr)
print('-'*20)

# ✅ Task 3: Replace all values > 50 with 999
a = np.array([10, 55, 23, 88, 34])
a[a>50] =999
print(a)

print()
print('-'*20)

#Task 4: Element-wise subtraction of two arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a-b)
print()

# ✅ Task 5: Use broadcasting to subtract a scalar
arr = np.array([5, 10, 15])
print(arr-2)
print()
print('-'*20)

# Task 6: Calculate row-wise sum of 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.sum(axis = 1))
print('-'*20)

#Task 7: Square each element using broadcasting
arr = np.array([1, 2, 3, 4])
print(arr**2)
print('-'*20)

# Task 8: Conditional extraction
arr = np.array([10, 15, 20, 25, 30])
fil = arr[arr>15]
print(fil)
print('-'*20)

# ✅ Task 9: Logical AND filtering
a = np.array([5, 10, 15, 20, 25])
fil = a[(a>10) & (a<20)]
print(fil)
print('-'*20)
# ✅ Task 10: Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
res = np.dot(a,b)
print(res)

[10 20 30 40 50]

[1 7 3 9 5]
--------------------
[ 10 999  23 999  34]

--------------------
[ 9 18 27]

[ 3  8 13]

--------------------
[ 6 15]
--------------------
[ 1  4  9 16]
--------------------
[20 25 30]
--------------------
[15]
--------------------
[[19 22]
 [43 50]]
