In [2]:
# creating array
# 1d array

import numpy as np

arr = np.array([1,2,3,4,5])
print(type(arr))

# 2D Array (Matrix)
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)


<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [5]:
# 🔹 Basic Array Operations
#✅ Math operations (faster than lists)

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
print(a/b)
print(a-b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[-3 -3 -3]


In [12]:
#🔹 Useful NumPy Functions
# 1. np.zeros() → Creates array of 0s
np.zeros((2,3))

np.ones((2,3)) # its mean fillled with 1 in 2 row and 3 column

np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [17]:
# np.arange() → Like range(), but returns an array
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [29]:
# np.linspace() → Evenly spaced numbers
''' 
uses: 
#) Evenly spaced values in a range (for graphs, sampling, scaling, etc.)
#) To generate values including both start and end points

How it Works:
0 = start

1 = end

5 = number of values you want
'''
print(np.linspace(0,1,5)) # 5 values came from 0 to 1
print('-'*10)
print(np.linspace(0,1,8)) # 8 values came from 0 to 1
print('-'*10)
print(np.linspace(0,5,6)) # 6 values came from 0 to 5

[0.   0.25 0.5  0.75 1.  ]
----------
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]
----------
[0. 1. 2. 3. 4. 5.]


In [34]:
#  Array Attributes (Properties)
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size) # total elements
print(arr.shape)  # (2, 3) → 2 rows, 3 columns
print(arr.ndim) # 2 → 2 dimensions
print(arr.dtype)


6
(2, 3)
2
int64


In [39]:
# 🔹 Indexing & Slicing
'''
a = np.array([10, 20, 30, 40])

print(a[1])      # 20
print(a[1:3])    # [20 30]

matrix = np.array([[1, 2], [3, 4]])
print(matrix[0, 1])  # 2 → Row 0, Col 1
'''


a = np.array([1,2,3,4,5])
print(a[1])
print(a[0:])
print(a[0:3])
print(a[0:5:3])

2
[1 2 3 4 5]
[1 2 3]
[1 4]


In [46]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix[1, 1]) # output : 5
print(matrix[1,0]) # output : 4
print(matrix[0,0]) # output : 1
print(matrix[0,2]) # outout : 3

5
4
1
3


In [47]:
#  Real-Life Example: Double all sales
sales = np.array([100,200,300,400,500])
doubled = sales * 2
print(doubled)

[ 200  400  600  800 1000]
