In [2]:
import numpy as np

#  Basic Slicing (1D Array)
a = np.array([1,2,3,4,5,6])
print(a[0])
print(a[-1])
print(a[0:])
print(a[3:])
print(a[0:5:2])
print(a[::-1])

1
6
[1 2 3 4 5 6]
[4 5 6]
[1 3 5]
[6 5 4 3 2 1]


In [17]:
# Indexing in 2D Array
arr2d = np.array([[1,2,3],
                 [4,5,6],
                  [7,8,9]])
print(arr2d)
print('dimension :',arr2d.ndim)
# # First row, first column
print("-"*20)
print(arr2d[0,0])
print("-"*20)

## Second row, third column
print(arr2d[1,2]) # dont confuse its working in indexing, index strarts from 0 right.
print("-"*20)

# # Last element
print(arr2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension : 2
--------------------
1
--------------------
6
--------------------
9


In [29]:
# Slicing in 2D Array
import numpy as np
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


print(arr2d[0:2, 1:]) # o:2 is mentioned row index from 0 to 1, 2is exclusive.  & 1:  mean column index from 1 to end
print()
print('-'*20)
# Get the first two columns of all rows.
print('first two columns of all rows:')
print(arr2d[0: , 0:2])
print('-'*20)
print()
print('Get the last row only, using slicing.')
print(arr2d[2:])
print('-'* 20)
print('Get the middle element (5) using slicing (not indexing directly)')
print(arr2d[1:2,1:2])

[[2 3]
 [5 6]]

--------------------
first two columns of all rows:
[[1 2]
 [4 5]
 [7 8]]
--------------------

Get the last row only, using slicing.
[[7 8 9]]
--------------------
Get the middle element (5) using slicing (not indexing directly)
[[5]]


In [39]:
# Get Diagonal Elements
print(np.diag(arr2d))
print("-"*20)
print ('2d array: ')
print(arr2d)
print()
print('diagnal :',arr2d[[0,1,2],[0,1,2]]) 
print('-'*20)


[1 5 9]
--------------------
2d array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

diagnal : [1 5 9]
--------------------


In [50]:
#  Row & Column Accessing (2D Array)
print('2d array')
print(arr2d)
print('-'*20)
print()
#  Entire second row
print(' Entire second row')
print(arr2d[1])
print('-'*20)
print('All rows, second column')
print(arr2d[[0,1,2],[1]])
print()
print('this also working')
print(arr2d[:,1])

2d array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------

 Entire second row
[4 5 6]
--------------------
All rows, second column
[2 5 8]

this also working
[2 5 8]


In [75]:
# Boolean Indexing
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[arr>10])
arr>10
print('-'*20)
# Get all elements less than or equal to 20
print(arr[arr<=20])
print('-'*20)

# Get all elements between 10 and 25 (inclusive)
print(arr[(arr>10) & (arr<25)])

print('-'*20)
print('Get all even numbers')
print('array :',arr)
print('even :',arr[((arr)%2 == 0)])
print('-'*20)

'''
🔹 Task 4:
Replace all elements greater than 20 with -1
👉 Final array should look like: [5, 10, 15, 20, -1, -1]

'''
arr[arr>20] = -1
print(arr)

[15 20 25 30]
--------------------
[ 5 10 15 20]
--------------------
[15 20]
--------------------
Get all even numbers
array : [ 5 10 15 20 25 30]
even : [10 20 30]
--------------------
[ 5 10 15 20 -1 -1]


In [84]:
#   Fancy Indexing (Indexing with Arrays or Lists)  mean (Fancy indexing gives exact positions you specify)
'''
This is different from slicing (arr[0:3]) because:

Slicing gives a range

Fancy indexing gives exact positions you specify
'''
arr = np.array([100, 200, 300, 400])
print(arr[[1,3]]) # Fancy indexing gives exact positions you specify

arr = np.array([10, 20, 30, 40, 50])
# [20 30 50]
print(arr[[1,2,4]])
print()

# [50 10 20] (custom order!)
print(arr[[4,0,1]])
print()

# task
arr = np.array([5, 10, 15, 20, 25])
# Get elements at positions 0, 2, and 4 using fancy indexing
print(arr[[0,2,4]])



[200 400]
[20 30 50]

[50 10 20]

[ 5 15 25]


In [86]:
# ✅ 8. Slicing with Step
arr = np.array([0, 1, 2, 3, 4, 5, 6])
# # Every second element
print(arr[::2])
print()

#Get every third element from the array.
print('Get every third element from the array.')
print(arr[::3])

[0 2 4 6]

Get every third element from the array.
[0 3 6]


In [100]:
# Modifying Sliced Values

arr = np.array([10, 20, 30, 40, 50, 60, 70])

# task1 
'''
Change the middle three elements (30, 40, 50) to 0
👉 Expected Output: [10 20 0 0 0 60 70]
'''
print('array :',arr)
print()
arr[2:5] = 0
print(arr)
print('-'*20)

# Replace the first three elements with -1
arr[:3] = -1
print(arr)
print('-'*20)

# Replace the last two elements with 100
arr[5:] = 100
print(arr)


print('-'*20)
# Double the value of the first four elements using slicing
arr1 = np.array([10, 20, 30, 40, 50, 60, 70])
arr1[:4] = arr1[:4]*2
print(arr1)


array : [10 20 30 40 50 60 70]

[10 20  0  0  0 60 70]
--------------------
[-1 -1 -1  0  0 60 70]
--------------------
[ -1  -1  -1   0   0 100 100]
--------------------
[20 40 60 80 50 60 70]


In [117]:
#  Using np.where() for conditional indexing

arr = np.array([5, 10, 15, 20])

result = np.where(arr > 10)
print('this is indices: ',result)
print('this is values: ',arr[result])

print()
print('Task1 : Find the indices where values are less than 15')
task1 = np.where(arr<15)
print('this is indices: ',task1)
print('this is values: ',arr[result])
print()
print('task 2')
print('Use np.where() to replace values greater than 10 with -1')
arr = np.array([5, 10, 15, 20])
task2 = np.where(arr>10,-1,arr) # # if value > 10, replace with -1, else keep original
print(task2)




this is indices:  (array([2, 3]),)
this is values:  [15 20]

Task1 : Find the indices where values are less than 15
this is indices:  (array([0, 1]),)
this is values:  [15 20]

task 2
Use np.where() to replace values greater than 10 with -1
[ 5 10 -1 -1]


In [5]:
import numpy as np

a = np.array([[[1,2],
               [3,4]],
              [[5,6],
               [7,8]]
             ])
print('dimension :',a.ndim)
# # First block, second row, second column
print(a[0,1,1])


dimension : 3
4


In [14]:
# tasks
#Create a 1D NumPy array with values [2, 4, 6, 8, 10].
a = np.array([1,2,3,4,5])
print(a[[0,-1]]) # Print the first and last element using indexing.
print('-'*20)

'''
Task:
Slice the array [10, 20, 30, 40, 50, 60] to get a new array containing only [20, 30, 40].
'''
a1  = np.array([10, 20, 30, 40, 50, 60])
print(a1[1:4])
print('-'*20)

'''
Task:
Reverse the array [1, 3, 5, 7, 9] using slicing.
'''
a2 = np.array([1, 3, 5, 7, 9])
print(a2[::-1])

[1 5]
--------------------
[20 30 40]
--------------------
[9 7 5 3 1]


In [20]:
# task print The element 22
a3 = arr = np.array([[11, 12, 13],
                [21, 22, 23],
                [31, 32, 33]])
print(a3[1,1])
print('-'*20)
print ('task 2')

# task 2 : From the same array above, slice the middle 2x2 block:
[[22, 23],
 [32, 33]]

print(a3[1:,1:])

22
--------------------
task 2
[[22 23]
 [32 33]]


In [21]:
# From the array [5, 12, 17, 8, 24], use boolean indexing to get values greater than 10.
a4  = np.array([5, 12, 17, 8, 24])
result = a4>10
print(a4[result])

[12 17 24]


In [23]:
# Given arr = np.array([10, 20, 30, 40, 50]), use fancy indexing to get [50, 10, 30].
a5 = np.array([10, 20, 30, 40, 50])
print(a5[[4,0,2]])

[50 10 30]


In [25]:
'''
✅ Exercise 8: Conditional Replace (Boolean Indexing)
Task:
From the array [3, 9, 12, 7, 5], replace all values greater than 8 with 0.
'''
a6 = np.array([3, 9, 12, 7, 5])
greater = a6>8
a6[greater] = 0
print(a6)


[3 0 0 7 5]


In [26]:
'''
✅ Exercise 9: Step Slicing
Task:
Create an array of numbers 0 to 20. Slice it to get every third element.
'''
a7 = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(a7[0::3])

[ 0  3  6  9 12 15 18]


In [27]:
'''
✅ Exercise 10: np.where() Use
Task:
From the array [4, 7, 2, 9, 5], find the indices of values less than 6, and extract those values.
'''
a8 = np.array([4, 7, 2, 9, 5])
result = np.where(a8<6)
print(result)

(array([0, 2, 4]),)
